# Generated by Django 5.2.3 on 2025-06-20 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_APP', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecture',
            old_name='vieo_url',
            new_name='video_url',
        ),
    ]
